# This is a workflow to help building sphinx-documentation

name: sphinx-doc

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
    - issue_8
    paths:
    - docs/**
    - src/**
    pull_request:
    branches:
    - issue_8
    

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies and commit doc changes
    # Publish built docs to gh-pages branch.
    # ===============================
      run: |
        mkdir docs/_build && mkdir docs/_autosummary && mkdir docs/_static && mkdir docs/_templates && chmod gou+wrx -R docs
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.7.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/_build/html/
